# Generated by Django 2.2 on 2021-07-06 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wall_app', '0002_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='msg_text',
            new_name='message_text',
        ),
    ]
