# Generated by Django 2.2 on 2021-07-06 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall_app', '0003_auto_20210706_0404'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
