# Generated by Django 2.2 on 2021-07-09 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wall_app', '0006_message_liked_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='liked_by',
        ),
    ]
