# Generated by Django 2.2 on 2021-07-10 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wall_app', '0008_auto_20210709_0419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='message',
            field=models.ForeignKey(default='message', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='wall_app.Message'),
        ),
    ]
